/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Mon Dec 18 21:38:43 1995
 */
extern int angles ( double *p, double *q, double *e );
extern double arcdot ( double *p, double *q );
extern int domoon ( double TDT, double *pol );
extern int moonll ( double J, double *moonpp, double *moonpol );
extern int gmoon ( double J, double *rect, double *pol );
extern double mods3600 ( double x );
extern int chewm ( short *p, int nlines, int nangles, int typflg, double *ans );
extern double deltat ( double Y );
extern int update (double &TDT, double &JD, double &UT, int jdf);
extern double mod360 ( double x );
extern double modtp ( double x );
extern int deltap ( double *p0, double *p1, double *dr, double *dd );
extern int epsiln ( double J );
extern int gplan ( double J, struct plantbl *plan, double *pobj );
extern int g3plan ( double J, struct plantbl *plan, double *pobj, int obj );
extern int kepler ( double J, struct orbit *e, double *rect, double *polar, double *eclip);
extern int embofs ( double J, double *emb, double *r );
extern int lonlat ( double *pp, double J, double *polar, int precess );
extern int nutlo ( double J );
extern int nutate ( double J, double *p );
extern int sscc ( int k, double arg, int n );
extern int precess ( double *R, double J, int direction );extern int reduce ( struct orbit *elemnt, double *q, double *e, double *pol, double TDT) ;
extern double sidrlt ( double j, double tlong, double TDT );
extern int dosun ( double TDT, double &rads );
extern int velearth ( double J );
extern double zatan2 ( double x, double y );
extern int initearth(double TDT );
extern int dotheplanet( double TDT, int i, double *robj, double *polar, double *eclip );
extern int doplanet(double TDT, struct orbit *eleobj, double *robj, double *ear, double *polar, double *eclip);
extern int dostar(int i, double j, double *pol );
extern int fk4fk5( double *p, double *m, struct star *el );
extern int domessier(int i, double j, double *pol );